# Generated by Django 4.1.7 on 2023-08-14 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Indicator",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_residential_electricity_use", models.FloatField()),
                ("number_of_people_with_regular_connection", models.FloatField()),
                (
                    "total_electricity_consumption_in_public_buildings",
                    models.FloatField(),
                ),
                ("total_area_of_these_buildings", models.FloatField()),
                (
                    "total_electricity_consumption_produced_from_renewable",
                    models.FloatField(),
                ),
                ("total_energy_consumption", models.FloatField()),
                ("total_electricity_use", models.FloatField()),
                ("total_number_of_consumer_interruptions", models.FloatField()),
                ("total_number_of_consumers_served", models.FloatField()),
                ("sum_of_the_duration_of_all_interruptions", models.FloatField()),
                ("total_number_of_interruptions", models.FloatField()),
                ("population", models.FloatField()),
                ("city", models.CharField(default="Goiânia", max_length=50)),
                ("is_certified", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicators",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
    ]
