# Generated by Django 4.1.7 on 2023-08-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indicators", "0002_alter_indicator_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="name",
            field=models.CharField(default="Nome", max_length=50),
            preserve_default=False,
        ),
    ]
