# Generated by Django 4.1.7 on 2023-11-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LocationStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_usina",
                    models.CharField(max_length=255, verbose_name="Nome da Usina"),
                ),
                ("latitude", models.FloatField(default=0.0, verbose_name="Latitude")),
                ("longitude", models.FloatField(default=0.0, verbose_name="Longitude")),
                ("city", models.CharField(max_length=255, verbose_name="Cidade")),
                (
                    "average_photovoltaic_irradiation",
                    models.FloatField(default=0.0, verbose_name="Media por ano KhW"),
                ),
                ("state", models.CharField(max_length=255, verbose_name="Estado")),
            ],
            options={
                "verbose_name": "Localização",
            },
        ),
    ]
