# Generated by Django 4.1.7 on 2023-10-24 15:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("energy_converter", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="locationsstations",
            options={
                "verbose_name": "locations_station",
                "verbose_name_plural": "locations_stations",
            },
        ),
    ]
