# Generated by Django 4.1.7 on 2023-10-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("energy_converter", "0002_alter_locationsstations_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_usina",
                    models.CharField(max_length=255, verbose_name="Nome da Usina"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Latitude"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Longitude"
                    ),
                ),
                ("city", models.CharField(max_length=255, verbose_name="Cidade")),
                ("state", models.CharField(max_length=255, verbose_name="Estado")),
            ],
            options={
                "verbose_name": "Localização",
                "verbose_name_plural": "Localizações",
            },
        ),
    ]
