# Generated by Django 4.1.7 on 2023-10-24 16:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("energy_converter", "0003_locationstation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="locationstation",
            options={"verbose_name": "Localização"},
        ),
    ]
