# Generated by Django 4.1.7 on 2023-10-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("energy_converter", "0004_alter_locationstation_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationstation",
            name="average_photovoltaic_irradiation",
            field=models.DecimalField(
                decimal_places=6,
                default=2,
                max_digits=9,
                verbose_name="Average Photovoltaic Irradiation",
            ),
            preserve_default=False,
        ),
    ]
