# Generated by Django 4.1.7 on 2023-08-13 03:36

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_alter_profile_twitter_handle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="country",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="followers",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="profile_photo",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="twitter_handle",
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+5562982622387",
                max_length=30,
                region=None,
                verbose_name="phone number",
            ),
        ),
    ]
