# Generated by Django 4.1.7 on 2023-09-17 00:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="State",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("sigla", models.CharField(max_length=2, verbose_name="sigla")),
                ("nome", models.CharField(max_length=50, verbose_name="nome")),
            ],
            options={
                "verbose_name": "state",
                "verbose_name_plural": "states",
            },
        ),
    ]
