# Generated by Django 4.1.7 on 2023-11-05 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("energy_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("acronym", models.CharField(max_length=2, unique=True)),
                ("population", models.IntegerField()),
                (
                    "data_energetic",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="energy_data.dataenergetic",
                    ),
                ),
            ],
        ),
    ]
