# Generated by Django 4.1.7 on 2023-11-24 19:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataEnergetic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_residential_electricity_use", models.FloatField()),
                ("number_of_people_with_regular_connection", models.FloatField()),
                (
                    "total_electricity_consumption_in_public_buildings",
                    models.FloatField(),
                ),
                ("total_area_of_these_buildings", models.FloatField()),
                (
                    "total_electricity_consumption_produced_from_renewable",
                    models.FloatField(),
                ),
                ("total_energy_consumption", models.FloatField()),
                ("total_electricity_use", models.FloatField()),
                ("total_number_of_consumer_interruptions", models.FloatField()),
                ("total_number_of_consumers_served", models.FloatField()),
                ("sum_of_the_duration_of_all_interruptions", models.FloatField()),
                ("total_number_of_interruptions", models.FloatField()),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("is_certified", models.BooleanField(default=False)),
                (
                    "data_energetic",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="projects.dataenergetic",
                    ),
                ),
                (
                    "location",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="locations.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "project",
                "verbose_name_plural": "projects",
            },
        ),
    ]
