# Generated by Django 4.1.7 on 2023-10-20 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_dataenergetic_location_project_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="data_energetic",
        ),
        migrations.AddField(
            model_name="location",
            name="data_energetic",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="projects.dataenergetic",
            ),
            preserve_default=False,
        ),
    ]
