# Generated by Django 4.1.7 on 2023-10-20 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_remove_project_data_energetic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="data_energetic",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="projects.dataenergetic",
            ),
        ),
    ]
