# Generated by Django 4.1.7 on 2023-10-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_alter_location_data_energetic"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="slug",
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
