# Generated by Django 4.1.7 on 2023-10-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_alter_location_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
