# Generated by Django 4.1.7 on 2023-10-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0008_alter_location_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="type",
            field=models.CharField(default="C", max_length=1),
        ),
    ]
